# Generated by Django 5.2.6 on 2025-10-17 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('year_of_study', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5')], max_length=1)),
                ('exam_type', models.CharField(choices=[('resit', 'Resit'), ('retake', 'Retake'), ('special', 'Special')], max_length=10)),
                ('unit_name', models.CharField(max_length=200)),
                ('unit_code', models.CharField(max_length=50)),
                ('year_taken', models.IntegerField()),
                ('semester_taken', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1)),
                ('supporting_document', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted - Pending Officer Review'), ('under_review', 'Under Review by Officer'), ('approved', 'Approved - Forwarded to Lecturer'), ('rejected', 'Rejected by Officer'), ('exam_received', 'Exam Script Received by Lecturer'), ('marking_complete', 'Marking Complete'), ('submitted_to_officer', 'Submitted to Exam Officer'), ('uploaded_to_portal', 'Uploaded to Portal')], default='submitted', max_length=30)),
                ('auto_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(choices=[('SOB', 'School of Business'), ('SOE', 'School of Engineering'), ('SOS', 'School of Science'), ('SOH', 'School of Humanities'), ('SOCS', 'School of Computer Science'), ('SOL', 'School of Law'), ('SOM', 'School of Medicine'), ('GENERAL', 'General Office')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_officers',
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exam_portal.examapplication')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exam_portal.examofficer')),
            ],
            options={
                'db_table': 'application_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(choices=[('SOB', 'School of Business'), ('SOE', 'School of Engineering'), ('SOS', 'School of Science'), ('SOH', 'School of Humanities'), ('SOCS', 'School of Computer Science'), ('SOL', 'School of Law'), ('SOM', 'School of Medicine')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecturers',
            },
        ),
        migrations.CreateModel(
            name='ExamMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking', to='exam_portal.examapplication')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings', to='exam_portal.lecturer')),
            ],
            options={
                'db_table': 'exam_markings',
            },
        ),
        migrations.AddField(
            model_name='examapplication',
            name='assigned_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='exam_portal.lecturer'),
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('ocr_summary', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('keywords_found', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='exam_portal.examapplication')),
            ],
            options={
                'db_table': 'ocr_results',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('school', models.CharField(blank=True, choices=[('SOB', 'School of Business'), ('SOE', 'School of Engineering'), ('SOS', 'School of Science'), ('SOH', 'School of Humanities'), ('SOCS', 'School of Computer Science'), ('SOL', 'School of Law'), ('SOM', 'School of Medicine')], max_length=10, null=True)),
                ('program', models.CharField(blank=True, choices=[('BSC_CS', 'BSc Computer Science'), ('BSC_IT', 'BSc Information Technology'), ('BBA', 'Bachelor of Business Administration'), ('BENG_CE', 'BEng Civil Engineering'), ('BENG_EE', 'BEng Electrical Engineering'), ('BSC_MATH', 'BSc Mathematics'), ('BSC_PHYS', 'BSc Physics'), ('BA_ECON', 'BA Economics'), ('LLB', 'Bachelor of Laws'), ('MBCHB', 'Bachelor of Medicine')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('status_update', 'Status Update'), ('officer_message', 'Message from Officer'), ('lecturer_message', 'Message from Lecturer'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exam_portal.examapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exam_portal.student')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='examapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exam_portal.student'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('officer', 'Exam Officer'), ('lecturer', 'Lecturer')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to='exam_portal.lecturer')),
            ],
            options={
                'db_table': 'unit_assignments',
                'unique_together': {('lecturer', 'unit_code', 'year', 'semester')},
            },
        ),
    ]
